title: "portfolio"
description: "where the stuff and things go"
baseurl: ""
url: "https://ashleyjohnson90.github.io/"

permalink: pretty
exclude:
  - demo/
  - cvless.gemspec
  - LICENSE
  - README.md
  - screenshot.png

# author settings
author:
  name: Ashley Johnson
  email: ashley.johnson73@snhu.edu
photo:
address: cambridge city, in
phone: 765.914.4787

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
